### ISSUE TITLE
Latest update broke non-automated generator speed

### ISSUE THREAD

**Issue by DefaultRyan** [zephyron1237/adcom-mission-tracker#18]
Say, I unlock Coast Guards, but I have not unlocked the researcher for them. I used to be able to set my Coast Guard speed to anywhere between 0 and 1 (usually 0.5 for me) to indicate that I was running that generator manually. This gave much better calculations.

Now, post-update, any generator that doesn't have the researcher unlocked is assumed to run at speed 0! Not good.

Please restore some way of getting this functionality back, either by allowing users to override a researcher speed manually, or by having a global setting for the speed of non-automated generators.

**Comment by zephyron1237** [comment]
Hi.  Thanks for creating this issue and your patience.  I'm extremely sorry this took so long, especially since this was a useful feature of the previous version that the redesign broke... things have been a bit hectic for me.  I have just pushed out the change 81981ea which should hopefully resolve this.  The change adds a '#' button to all researchers at level 0 that allows you to specify an override for that researcher's value.  Overriding the relevant common's speed to 0-1x should work as it used to for simulating manual runs.

I'm going to close this for now, but please let me know if you have any issues or other concerns.
