### ISSUE TITLE
Wrong researcher name in ninja event

### ISSUE THREAD

**Issue by The-Snide-Sniper** [zephyron1237/adcom-mission-tracker#28]
The researcher for kaijus is listed with the name "targaricent". However, I know that this is wrong because I've unlocked that researcher in-game, and its listed name is Xilien Fairies. Is this just a mistake or is there a reason for it?

**Comment by zephyron1237** [comment]
The data in the tracker is based on the balance configuration.  The balance config does contain a number of strings for things like names, but AFAIK none of those strings are actually used in-game.  Instead there is a separate Localization configuration that has every string visible in the game for your local language.  Unfortunately, this means that the strings in the config do not have to be correct, and sometimes aren't, like capitalization, or accidentally leaving the third resource as "Lasers" when they remade Space into Cowboy.

I had previously hoped that I could avoid including the Localization, both to simplify updating the tracker and to avoid adding another 200kb worth of download before the tracker properly loads, but data.js is already nearly 1.5mb, so it's probably not a big deal at this point.

I have fixed this specific issue as of d7b9dbd and I'll create an issue to base displayed strings on the Localization file for the future.  Thanks again for all your contributions.  I'll probably take a close look at your PR in the next day or two since I'm starting to feel better.
