### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by EdricChan03** [zephyron1237/adcom-mission-tracker#33]
I suppose the repository could do with some [issue templates](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository), now that it's starting to gain a bit of traction in issues.

**Comment by zephyron1237** [comment]
While I think issue templates make a lot of sense for a lot of projects, I'm not sure I like the idea for the mission tracker.  Fundamentally, I think it's engineering a solution to a problem that I don't think exists.

One reason is that I think templates make more sense for projects that need to sort through a lot of issues or have multiple developers that you want to auto-assign certain tasks to.  Having a template allows you to standardize the information you get, but asks more of the people submitting issues.  Frankly, the bar is already probably too high for most users as is-- having to go to a site you never use (github) and register an account is actually asking a lot-- and since a lot of issues go unreported (I've found out about several just by seeing people complain on discord without tagging me or anything), I'd rather make the process easier rather than harder.

I'd also challenge the idea that the tracker is gaining traction in issues.  I get roughly one issue a month, and my goal is not to do any more feature development at this point (besides small bugfixes or assisting where somebody else is doing the majority of the work). Nobody has stepped up to do development work on anything but their own issues, which is understandable, but it means that the issue tracker is basically for me, and with how little I plan on working on the tracker, it doesn't seem helpful to add some standardization to the few issues that are submitted.

If somebody else ends seriously working on the tracker, it'll probably be a good idea to re-evaluate issue templates at that point, but until then I'm going to mark this as closed and wontfix.  Feel free to hit me up on Discord if you still feel strongly about templates.
