### ISSUE TITLE
Calculator ignores Unlock criteria to determine if you can buy the relevant generator(s)

### ISSUE THREAD

**Issue by patrickxia** [zephyron1237/adcom-mission-tracker#4]
This is a really minor problem because it can typically be solved by hand with a single division, but in the interest of completeness...

Here's an example: right now I have a mission to collect 70 trestles (`"Cost":[{"Resource":"SteamEngine","Qty":100000},{"Resource":"Railway","Qty":"1.0E+39"},{"Resource":"Comrade","Qty":"2"}]`), with `"Unlock":{"ConditionType":"ResourceQuantity","ConditionId":"steamengine","Threshold":100000000}`.

I have 500 II railways, so I have enough to immediately just buy the 70 trestles. The problem is that I don't have the 100 M steam engines to unlock the trestles, and I'm comrade limited there, so the estimated time of 0:00:00 is incorrect.

**Comment by zephyron1237** [comment]
Thanks for the detailed report.  While this is technically an issue, it is documented in the Details/Tips section of the popup ("The calculator currently does not take airdrops or unlocking new generators into account.").  It's been pretty low on my priority list, especially since nobody has requested it until now, but that bumps it up a bit... though it may still be a while before I get around to it.  If you're feeling motivated, you're welcome to submit a PR :)

**Comment by zephyron1237** [comment]
Thanks again for the report and request.  Finally, this feature has been implemented.  As of f6be8a2, when the Autobuy option is enabled, the deepest generator to be autobought will be updated as they get unlocked.  So you can, for example, start a Sky Farm mission with just 1 Farmer and Autobuy if your researchers are set up.
